### Verify Row Echelon Form
1. The nonzero rows of a matrix in echelon form are above any zero rows.
2. The leading entry of each row is to the right of the leading entries of the rows above.
3. The entries below a leading entry are zero.

In [2]:
import numpy as np

from testMatricies import getTestMatrices



def verifyZeroRowOrder(matrix):

    order  = []

    for row in matrix:

        if isZeroRow(row):
            order.append(0)
        else:
            order.append(1)
            
    zero_found = False

    for num in order:
        if num == 0:
            zero_found = True
        elif num == 1 and zero_found == True:
            return False

    return True

def isZeroRow(row):
    for elem in row:
        if elem != 0:
            return False
    return True

def getPivotIndexs(matrix):

    pivot_indexes = []
    rows = matrix.shape[0]

    for i in range(0, rows):
        row = matrix[i]
        for j in range(0, len(row)):
            elem = row[j]
            if elem != 0:
                pivot_indexes.append((i, j))
                break

    return pivot_indexes


def verifyLeadingEntries(matrix):
    pivot_indexes = getPivotIndexs(matrix)

    pivotColums = []
    for elem in pivot_indexes:
        pivotColums.append(elem[1])


    for i in range(0, len(pivot_indexes)):
        index = pivot_indexes[i]
        # skip first row
        if index[0] != 0:
            curCol = index[1]
            prevCol = pivot_indexes[i-1][1] 

            if curCol <= prevCol:
                return False
    return True


def runTests(matrix):
    print(matrix)

    if verifyZeroRowOrder(matrix) == False:
        print("is not in echelon form")
        print("zero row rule")
        return


    if verifyLeadingEntries(matrix) == False:
        print("is not in echelon form")
        print("row pivot colum order rule")
        return

            
def main():
    # ref
    testMatrices = getTestMatrices()
    matrix = testMatrices["breakPivotCol"]
    runTests(matrix)

if __name__ == '__main__':
    main()

[[ 3 -2  6  0  1]
 [ 0  0  0 -3  5]
 [ 0  0  2  7  5]
 [ 0  0  0  0  0]]
is not in echelon form
row pivot colum order rule
